version: '3.8'

services:
  superset:
    build: 
      context: .
      dockerfile: Dockerfile.superset
    image: apache/superset:custom
    container_name: superset
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=tu_clave_secreta_muy_segura_aqui
      - SUPERSET_ENABLE_CORS=true
      - SUPERSET_ENABLE_PROXY_FIX=true
      - FLASK_APP=superset.app:create_app()
      - FLASK_ENV=development
    volumes:
      - superset_data:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    container_name: superset_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
      - POSTGRES_DB=superset
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: superset_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
  
  nginx:
    image: nginx:latest
    container_name: superset_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - superset



volumes:
  superset_data:
  db_data:
  redis_data: